language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- python setup.py -q install
script:
- nosetests
deploy:
  provider: pypi
  user: Gohla
  password:
    secure: pljvGeCvThdDJvBRMLLCp5rg6R2KcE0VBlb2fUXt7/SI5MvfxT6hU2eahjWva1OJjJJywY82JD+Oanlw6ZFa7+5VZqcdeeQkY6YkqfVt/IFuelz++rZWeLd6iyxFmElFsJdI0DNCs3GOCHr442ui5C163Pc8pgVSXzRsNfhHJ2OVDBxOIvNX0TEigJe3O8MI7Vaqm+aNSkAVaVvpycNQrnfAjAuOaczWftrJfotMS2f40IVo2eUb4A+eLx5xiMhlSXG7WShqG7dPTGWZfFubWAH5q4ZbPLmrfEQzhOP/9in/5H3NNh3B+oyiaidDtsxqrZXPzkW6Jpp85z25YdGIsnQNBiLJMsUSzfL1TnVB347hYyRjLgfDnmIvMq/4VEI9l9t/ZQ0YOxcm4BmyPb2x8fGB+EP6J8pb98QQLm/L/qXdG/f+pLd1013/R+ToRY2ZBqx/FOUtwXLWitVKh4ZJfd1OpY0eQflxiXUHxR3GwogoTOPIm6RpDPiSWc+qejoD5nZU+QgP6DseYKS4Fj/ijVT2HuYGhUUaqJgrmNtVQZ0Aic2DK+MNwbsRmlWJTOWcabmkcFRFbxX6rslwMtUmGyP3m7kLH8X5W1miW4Vs36spyxqc9UXiAr11e61xovzHQJLuhikgjkJhbiJPtdaeH/8iQ6PRParvbMP9WHrRfH0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Gohla/gradlepy
